# Generated by Django 4.1.2 on 2022-10-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0010_alter_thread_options_thread_last_replied_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="last_replied",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="thread",
            name="last_replied_user",
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
    ]
