# Generated by Django 4.1.2 on 2022-10-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0011_alter_thread_last_replied_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="last_replied",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
