# Generated by Django 4.1.2 on 2022-10-14 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0012_alter_thread_last_replied"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["date_created"]},
        ),
    ]
