# Generated by Django 4.1.2 on 2022-10-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0013_alter_post_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="board",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="thread",
            options={"ordering": ["-is_sticky"]},
        ),
        migrations.RemoveField(
            model_name="board",
            name="no_of_posts",
        ),
        migrations.RemoveField(
            model_name="board",
            name="no_of_threads",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="last_replied",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="last_replied_user",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="no_of_posts",
        ),
        migrations.AddField(
            model_name="thread",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="thread",
            name="author_username",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=150,
                null=True,
                verbose_name="Author username",
            ),
        ),
    ]
