# Generated by Django 4.1.2 on 2022-10-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0015_alter_thread_options_remove_thread_date_created_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="thread",
            options={"ordering": ["-is_sticky"]},
        ),
        migrations.RemoveField(
            model_name="thread",
            name="last_replied",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="last_replied_user",
        ),
    ]
