# Generated by Django 4.1.2 on 2022-10-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_administrator",
            field=models.BooleanField(
                default=False, verbose_name="administrator status"
            ),
        ),
    ]
