# Generated by Django 4.1.2 on 2022-10-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_is_administrator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="about_myself",
            field=models.TextField(verbose_name="About myself"),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(verbose_name="Date of Birth"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email address"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="First name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Others")],
                max_length=2,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="hometown",
            field=models.CharField(max_length=50, verbose_name="Hometown"),
        ),
        migrations.AlterField(
            model_name="user",
            name="interests",
            field=models.TextField(blank=True, max_length=200, verbose_name="Interest"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_administrator",
            field=models.BooleanField(
                default=False, verbose_name="Administrator status"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_banned",
            field=models.BooleanField(default=False, verbose_name="Banned status"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_moderator",
            field=models.BooleanField(default=False, verbose_name="Moderator status"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_poster",
            field=models.BooleanField(default=True, verbose_name="Poster status"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="Last name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="present_location",
            field=models.CharField(max_length=100, verbose_name="Present location"),
        ),
        migrations.AlterField(
            model_name="user",
            name="website",
            field=models.CharField(blank=True, max_length=50, verbose_name="Website"),
        ),
    ]
