# Generated by Django 4.1.2 on 2022-10-19 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_avatar_url"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
