# Generated by Django 4.1.2 on 2022-10-21 08:32

import bulletinboard.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", bulletinboard.accounts.models.CustomUserManager()),
            ],
        ),
    ]
